# Simulations settings #########################################

HOME_DIR: /home/red/hugo-shadow-bft-starter
TARGET: /home/red/hugo-shadow-bft-starter/results
SHADOW_DIR: /home/red/shadow
BFT_SMART_DIR: /home/red/hugo-shadow-bft-starter/library
NUMBER_OF_NODES: 7
NUMBER_OF_REPLICAS: 4
NUMBER_OF_CLIENTS: 3



# In here we can override system settings #######################

# secretKeyAlgorithm: PBKDF2WithHmacSHA1
# secretKeyAlgorithmProvider: SunJCE
# hashAlgorithm: SHA-256
# hashAlgorithmProvider: SUN
# signatureAlgorithm: SHA256withECDSA
# signatureAlgorithmProvider: BC
# defaultKeyLoader: ECDSA
# useSenderThread: true
# defaultkeys: true
# bindaddress: auto
# inQueueSize: 500000
# outQueueSize: 500000
# useSignatures: 0

# batchtimeout: -1
# fairbatch: true
# nonces: 10
# verifyTimestamps: false
# state_transfer: true
# highMark: 10000
# revival_highMark: 10
# timeout_highMark: 200
# log: true
# log_parallel: false
# log_to_disk: false
# sync_log: false
# checkpoint_period: 1024
# global_checkpoint_period: 120000
# checkpoint_to_disk: false
# sync_ckp: false
# maxBatchSizeInBytes: 999999999
# maxbatchsize: 1000
# timeout: 2000

# protocol_version: TLSv1.2
# key_store_file: EC_KeyPair_256.pkcs12
# enabled_ciphers: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

# ttp.id: 7002

# shutdownhook: true
# samebatchsize: false
# numrepliers: 16
# bft: true
# initial.view: 0,1,2,3

# servers.num: 4
# servers.f: 0

# client.invokeOrderedTimeout: 40